name: Dependencies GitHub Comment
description: Write list of dependencies as a markdown table in a GitHub comment on the pull request
inputs:
  dependencies:
    description: 'Dependencies to generate markdown for'
    required: true
  token:
    description: 'GitHub token for authorizing adding comments'
    required: true
  comment-id:
    description: 'The ID of the GitHub comment, for updating comment if existing'
    default: 'dependencies-comment'
runs:
  using: node16
  main: lib/index.js
